image: gitlab/dind

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/image-quality-assessment/biqa-minion-matlab-base .
    - docker push registry.gitlab.com/image-quality-assessment/biqa-minion-matlab-base
